# Generated by Django 2.2.6 on 2019-10-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('vesselid', models.CharField(max_length=200)),
                ('coid', models.CharField(max_length=200)),
                ('template', models.TextField()),
                ('defaul', models.TextField()),
            ],
        ),
    ]
